### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by brizzer** [manticorp/GCodeArcOptimiser#5]
I like to port the code to python for use in cura or octoprint. Could you provide a licence so I can share (or not)? Regards.

**Comment by manticorp** [comment]
Sure you have my permission to do whatever you want with this repo! 
-------- Original message --------From: brizzer <notifications@github.com> Date: 10/02/2019  20:42  (GMT+00:00) To: manticorp/GCodeArcOptimiser <GCodeArcOptimiser@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [manticorp/GCodeArcOptimiser] Missing licence (#5) I like to port the code to python for use in cura or octoprint. Could you provide a licence so I can share (or not)? Regards.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/manticorp/GCodeArcOptimiser","title":"manticorp/GCodeArcOptimiser","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/manticorp/GCodeArcOptimiser"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Missing licence (#5)"}],"action":{"name":"View Issue","url":"https://github.com/manticorp/GCodeArcOptimiser/issues/5"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/manticorp/GCodeArcOptimiser/issues/5",
"url": "https://github.com/manticorp/GCodeArcOptimiser/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by manticorp** [comment]
Added a license - free to use for whatever you want!
